[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/download"
  to = "https://github.com/thanontos/protractorpro-releases/releases/latest/download/ProtractorProSetup.exe"
  status = 302
